name: 'Firmware Compile Action'
description: 'Unzip libraries and compile firmware'
inputs:
  enable-warnings-report:
    description: 'Enable warnings report'
    default: 'false'
  enable-deltas-report:
    description: 'Enable deltas report'
    default: 'false'
  sketches-report-path:
    description: 'Sketches report path'
    default: 'sketches-reports'
runs:
  using: 'composite'
  steps:
    - name: Unzip libraries
      shell: bash
      run: |
        unzip -q ${{ github.workspace }}/libs/Adafruit_GFX_Library.zip -d ${{ github.workspace }}/libs/
        unzip -q ${{ github.workspace }}/libs/ArduinoAsync-master.zip -d ${{ github.workspace }}/libs/
        unzip -q ${{ github.workspace }}/libs/melody-player-2.4.0.zip -d ${{ github.workspace }}/libs/
    - name: Compile firmware
      uses: arduino/compile-sketches@v1
      with:
        sketch-paths: |
          - ${{ github.workspace }}/src/firmware
        fqbn: esp32:esp32:esp32
        platforms: |
          - name: esp32:esp32
            source-url: https://github.com/espressif/arduino-esp32/releases/download/2.0.14/package_esp32_index.json
            version: 2.0.14
        cli-version: 1.0.3
        libraries: |
          - source-path: ${{ github.workspace }}/libs/Adafruit_GFX_Library
          - source-path: ${{ github.workspace }}/libs/ArduinoAsync-master
          - source-path: ${{ github.workspace }}/libs/melody-player-2.4.0
          - name: Adafruit SSD1306
            version: 2.5.9
          - name: Adafruit SH110X
            version: 2.1.10
          - name: ArduinoJson
            version: 7.0.4
          - name: ArduinoWebsockets
            version: 0.5.3
          - name: AsyncTCP
            version: 1.1.4
          - name: BH1750_WE
            version: 1.1.10
          - name: ESP Async WebServer
            version: 2.9.0
          - name: NTPTime
            version: 1.2.1
          - name: NeoPixelBus by Makuna
            version: 2.7.9
          - name: WiFiManager
            version: 2.0.17
          - name: arduino-sht
            version: 1.2.5
          - name: forcedBMX280
            version: 1.1.2
          - name: home-assistant-integration
            version: 2.1.0
        enable-warnings-report: ${{ inputs.enable-warnings-report }}
        enable-deltas-report: ${{ inputs.enable-deltas-report }}
        sketches-report-path: ${{ inputs.sketches-report-path }}
        cli-compile-flags: |
          - --export-binaries
          - --warnings=default
